### ISSUE TITLE
Pokemon Emerald Yoshi Menu wont show Open, save or any options

### ISSUE THREAD

**Issue by Madden20082008** [ITotalJustice/notorious_beeg#111]
when i go to the pokemon emerald launch page, none of the options like open, save import, or export. i dont know how to get it to show the option.

**Comment by ITotalJustice** [comment]
Hi, thanks for opening an issue.

Which platform are you having this issue on? Is it the web build? If so, what browser are you trying this with?

When you load a game, it should hide the menu. To get the menu back, you press this icon here 
![Screenshot_20230117-170826](https://user-images.githubusercontent.com/47043333/212965973-b5d86f09-2214-4a75-84fa-3f653ec72f4d.png)

Also, the on-screen controls auto hide themselves if you press a controller button or a keyboard key. This is because if you're not using the touch screen for controls, then no point covering screen with them. To get them back, simply touch the screen and they will appear.

Hope this helps!

**Comment by Madden20082008** [comment]
the menu that shows the expanding Yoshi isn't allowing me to open the game. all it shows is a black screen. this is on a Chromebook on google. the menu that pulls up when you push the 3 lines button isn't there. I cannot see the expanding Yoshi or the menu options. The green writing is all the stuff that is missing

![Screenshot 2023-01-17 11 39 04 AM](https://user-images.githubusercontent.com/122904757/212975069-f549fcfe-e782-4ad5-a193-6e2048e66a14.png) 
the green writing is what it should show but it is all missing
when I open the page https://itotaljustice.github.io/notorious_beeg/ it should show me the open, save, back, import and export options but it is just a black screen.

**Comment by ITotalJustice** [comment]
Ah I see the issue thank you! Looks like something broke with the GitHub hosting.

Can you try https://notorious-beeg.netlify.app/ and see if it works for you?

Were you using the website to play your games in the past? Like do you have save files and stuff on it? If so I'll try and quickly fix the GitHub URL for you so you can continue playing 😄

**Comment by ITotalJustice** [comment]
hi, the issue should be fixed now. you can force refresh the page by pressing `CTRL+SHIFT+R` .

![image](https://user-images.githubusercontent.com/47043333/213013287-f6c2492f-b3c9-42b0-8643-986ba3fce286.png)

let me know if it still persists!

**Comment by Madden20082008** [comment]
You fixed the issue. Thanks
